### ISSUE TITLE
read volumes from buildout.cfg file

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#1]
the idea with voodoo is that running inside Docker is an option but the repo should also be runnable directly on the host or via virtualenv. Hence, the place where to find the odoo repo or the shared eggs on the host is already expected to be present in the buildout.cfg.

So I propose that in voodoo.yml you can add or override volumes but by default we try to read the volumes for the host eggs and shared odoo from the buildout.cfg.
This logic was here in the bash launcher:
https://github.com/akretion/voodoo/blob/master/ak#L50
https://github.com/akretion/voodoo/blob/master/ak#L57

**Comment by sebastienbeau** [comment]
This have been implemented shared folder between host and container : https://github.com/akretion/voodoo/blob/master/voodoo/main.py#L85
