### ISSUE TITLE
psql with docky open

### ISSUE THREAD

**Issue by bealdav** [akretion/docky#101]
## Behavior

with docky run
```
odoo@9ba24327e5ba:/opt/odoo$ psql
psql (10.4 (Debian 10.4-2.pgdg80+1))
Type "help" for help.

db=# 
```

with docky open

```
odoo@9ba24327e5ba:/opt/odoo$ psql db
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
odoo@9ba24327e5ba:/opt/odoo$ 
```

## Desired behavior

the same whatever the both cmd

**Comment by rvalyi** [comment]
strange indeed. 1st thing I would check would be if we are entering the entry point with the same parameters/env variables. But it could also be a Docker compose issue, I hope not.

**Comment by hparfr** [comment]
It's because $PGUSER, $PGHOST, etc. are not loaded during docky open.

I think we should use `docker-compose exec` instead of `docker exec` : https://docs.docker.com/compose/reference/exec/
https://github.com/akretion/docky/blob/master/docky/cmd/run_open.py#L68

**Comment by hparfr** [comment]
It can be solved when declaring PG* vars in .env
