### ISSUE TITLE
missing git config --global user.email/name ?

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#103]
Hello, when running ak --verbose build with **merge** settings in my spec.yaml to be made (for instance merging branch akretion, 10.0-migration/l10n_br_account into branch OCA 10.0), git would fail with the following message:

```
(INFO) [01:08:59] git_aggregator.repo  Reset branch to kmee 10.0-mig-l10n_br_stock
(INFO) [01:08:01] git_aggregator.repo  Pull akretion, 10.0-migration/l10n_br_account

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <odoo@a748a62ae312.(none)>) not allowed
Traceback (most recent call last):
  File "/usr/local/bin/gitaggregate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/main.py", line 131, in main
    run(args)
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/main.py", line 174, in run
    r.aggregate()
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/repo.py", line 186, in aggregate
    self._merge(merge)
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/repo.py", line 253, in _merge
    self.log_call(cmd)
  File "/usr/local/lib/python2.7/dist-packages/git_aggregator/repo.py", line 156, in log_call
    ret = callwith(cmd, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(u'git', u'pull', u'--no-edit', u'--quiet', 'akretion', '10.0-migration/l10n_br_account')' returned non-zero exit status 128
Traceback (most recent call last):
```

and indeed doing
```
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
```
makes the next try to succeed.

So shouldn't we not have a fake git config in our base image just like we had in Voodoo? Something that could be overriden if we mount some config file or may be pass some ENV VAR. What do you think?

**Comment by bealdav** [comment]
why don't use ak outside of docker ?

**Comment by rvalyi** [comment]
@bealdav I agree that it would be better. But eventually we still put some fake git config in the image to avoid beginners to have troubles or if they didn't install ak properly outside of docker. Not sure, just thinking loud...

**Comment by hparfr** [comment]
Agree with @rvalyi , `ak build` should behave correctly inside and outside docker. 
Therefore git config --global should be done in the image.
A temp workaround is to add it to your project odoo/Dockerfile.

**Comment by hparfr** [comment]
Currently the preferred way is to run ak outside the container.
So closing this issue for the moment.
