### ISSUE TITLE
filestore loosing data

### ISSUE THREAD

**Issue by bealdav** [akretion/docky#104]
## Behavior
According to an unknown event (probably with docky exit but not always), 
my data_dir data is reset

Here is my configuration
```
[options]
addons_path = links,local-src,src/odoo/addons,src/addons
data_dir = /data/odoo
auto_reload = False

```
Data dir is available but reset by this event
```
odoo@490df08dae22:/data/odoo/filestore/db$ ls
c1  ce  checklist
```

## Desired behavior
Don't loose data

**Comment by hparfr** [comment]
Is it reproducible ?

**Comment by bealdav** [comment]
not

**Comment by rvalyi** [comment]
Hello, I had to mount a host volume to get my filestore persisted on the host. See how this line I added over the default shopinvader template:
https://github.com/akretion/odoo-brasil-docky/blob/10.0-oca/dev.docker-compose.yml#L35

Is it related? Should this be done in our Docky templates?

**Comment by bealdav** [comment]
I've done that but I have a problem with rights on this volume. Odoo can't write whereas odoo user own this folder.

Maybe something could be done in docky templates, yes.

**Comment by rvalyi** [comment]
git this issue again with the shopinvader-docky template.
Basically it uses /odoo/data because of this VOLUME statement in the Dockerfile:
```https://github.com/camptocamp/docker-odoo-project/blob/master/11.0/Dockerfile#L56```
it is then mounted in the host like (you can see that with docker inspect):
```/var/lib/docker/volumes/c8dda658ad09027242a5ee989e674738a9a6a937c29c9a1b849c7d30b61b8716/_data```
for some reason after I rebooted this host folder went empty for me so data were lost. I have no idea why this happens.
