### ISSUE TITLE
docky init is not compatible with published docky-template

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#139]
if you clone https://github.com/akretion/docky-odoo-template and start a fresh Docky project, you will have no .env file and your Docky projet will not work. So what you may probably do is `docky init` but then in the generated .env file you would be missing these environment variables to get things working properly:
```
PGHOST=db
PGDATABASE=demo
PGUSER=odoo
DB_USER=odoo
```

So what do we fix: the docky-odoo-template or docky init to make things user friendly?

**Comment by hparfr** [comment]
Short term: Add it in docky init.

**Comment by rvalyi** [comment]
(was my option too)

**Comment by hparfr** [comment]
Fixed.

You can test https://github.com/akretion/docky/pull/141
(don't forget to pip install -r requirements.txt)
