### ISSUE TITLE
.env file not filled on docky init

### ISSUE THREAD

**Issue by clementmbr** [akretion/docky#143]
Hi @hparfr (or anyone around here),
Am I missing something on `docky init`?

```
$ mkdir i2o
$ cd i2o/
$ docky init -b 14.0
🎤 env? Format: str dev
🎤 UID? Format: int 1000
🎤 PGHOST? Format: str db
🎤 PGDATABASE? Format: str db
🎤 PGUSER? Format: str odoo
$ cat .env 
UID={{UID}}
ENV={{env}}
COMPOSE_FILE=docker-compose.yml:{{env}}.docker-compose.yml:secrets.docker-compose.yml
COMPOSE_PROJECT_NAME={{project_name}}
PGHOST={{PGHOST}}
PGDATABASE={{PGDATABASE}}
PGPASSWORD={{PGPASSWORD}}
PGUSER={{PGUSER}}
```
I expected something more like :
```
$ cat .env 
UID=1000
ENV=dev
COMPOSE_FILE=docker-compose.yml:dev.docker-compose.yml:secrets.docker-compose.yml
COMPOSE_PROJECT_NAME=i2o
PGHOST=db
PGDATABASE=db
PGPASSWORD=odoo
PGUSER=odoo
```
Any idea why the .env is not filled ?

Thanks a lot! :pray:

**Comment by hparfr** [comment]
Hi,

Quite strange, it's like you got an old version of copier. Can you double check you got the last versions ?

Btw, if you want to test last branch: 
`docky init -b new-ci`

**Comment by rvalyi** [comment]
I think it has been fixed with the recent update of copier https://github.com/akretion/docky/commit/5f3ed4d46186915f216b2500f09de3089944199d
let's close it and re-open if still there.
