### ISSUE TITLE
ak build need to be done from /workspace

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#5]
ak build doesn't work if launched from somewhere else than /workspace. This is error prone for beginners. The problem seems to be when trying to find buildout.dec.cfg. I think it would be better to build an absolute path for it instead of using the path relative to the current file.

Possible use case: user start editng some local file and then wants to rebuild and ru the server again.

It probably affects ak run too. I fixed this already on Voodoo before 1.x when it was in plain bash.

**Comment by bealdav** [comment]
ok

**Comment by sebastienbeau** [comment]
Not sure it's a huge pain, /workspace is the default workdirectory. I thinks it's a must to have not a bug
