### ISSUE TITLE
command / plugin to test an OCA branch

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#6]
Would be cool to have a simple command (voodoo or ak, not sure) that could grab an OCA branch (may be a list of branches if there are dependencies) and then create a new database and installs a given module. That would allow us to be quick at testing OCA merge proposals, doing just one command and letting it build our test db in the background while we work on something different.

Eventually the command is flexible enough so as it can be used to test an improvement or hunt for a bug on our customer projects.

**Comment by sebastienbeau** [comment]
Implemented by benoit see : https://github.com/akretion/ak/commit/830f4aafa86670f4f18d838f8e80572ec59b2b68

**Comment by bealdav** [comment]
You shouldn't close, because there is no documentation of that and no one know use it

**Comment by EBII** [comment]
It is un docker documentation ans may use thé same command for postgres do ker
Docker exec -it -u root (postgres) container-id bash

Le 19 février 2017 09:45:50 GMT+01:00, David Beal <notifications@github.com> a écrit :
>You shouldn't close, because there is no documentation of that and no
>one know use it
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/akretion/voodoo/issues/6#issuecomment-280904910

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
