### ISSUE TITLE
require internet connection

### ISSUE THREAD

**Issue by bealdav** [akretion/docky#8]
with a native odoo installation you don't need internet.
with voodoo you need it.

You can't use it by train :-( 

Edit: with voodoo run

![voodooout](https://cloud.githubusercontent.com/assets/1853434/6959305/b73aaec4-d917-11e4-9f45-00d1332901a2.png)

Not in each case: chez le kiné ça pas marché, mais chez moi en enlevant le wifi si.

**Comment by sebastienbeau** [comment]
nop, this is a error because your docker service was out of work. You can try "sudo service docker.io restart"

**Comment by bealdav** [comment]
dommage que le message n'envoi pas "sudo service docker.io restart" =ment, 
dans l'optique de réutilisation de tous

**Comment by sebastienbeau** [comment]
le truc c'est que c'est une erreur de docker. En principe c'est qu'il n'est pas démarrer au qu'il y a une grosse merde. On pourrait essayer de catcher l'erreur mais pas évidant de trouver l'exact raison
