### ISSUE TITLE
ak run command is broken

### ISSUE THREAD

**Issue by clementmbr** [akretion/docky#88]
normally this `ak run shell` should launch the native odoo console but this is currently broken because of the way Voodoo messes up with the arguments.

Indeed; if we print args in odoo/cli/command; we get something like:
```
odoo@238f2bcf6054:/workspace$ ak run shell
['-c', '/workspace/etc/openerp.cfg', 'shell']
```
while the command argument is expected at the 1st position (command = args[0])

We should preserve the proper args ordering before forwarding args to odoo

**Comment by rvalyi** [comment]
it looks this is rather a problem inside the Anybox recipe, more specifically in
https://github.com/anybox/anybox.recipe.odoo/blob/master/anybox/recipe/odoo/runtime/start_odoo.py

Indeed bin/start_openerp seems to be called correctly by the ak command, but then in start_odoo.py, probably in the insert_args method, the config is appended before the Odoo command argument (here shell). Not sure how much it is worth looking at this if we plan to drop the recipe soon...

**Comment by rvalyi** [comment]
here is a work around to run the Odoo shell console in Voodoo:
https://gist.github.com/rvalyi/3cd204146c73449dd6e6df9394ffb8eb

**Comment by hparfr** [comment]
Not relevant anymore

(btw : it's now `odoo shell`)
