### ISSUE TITLE
ak run launch ak build after failed ak build

### ISSUE THREAD

**Issue by bealdav** [akretion/docky#9]
It seems that when I do an 'ak build' and for external reason it fails (i.e github blocking)
then when I run 'ak run', 'ak build' is launch.
So impossible to start a normal use

I suppose It's complicated to avoid it, it's like have a transactional ak build.

**Comment by bealdav** [comment]
if this case use ak build -o

**Comment by sebastienbeau** [comment]
Indeed if ak build failed the configuration file do not exist and as there is not sucessfull build done it we launch the ak run, the command line will re-run the build as it was not finish.
Running ak build -o launch the build in offline mode, so it can solve issue in case of lost of connection
