### ISSUE TITLE
new command is broken with docky

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#98]
docky new project or docky hep does'nt work because docky.yml file is missing which is actually normal when there is no project yet. It's a regression.

```
rvalyi@rvalyi-laptop:/tmp$ docky new test
Verbose mode activated
You can change the default value in ~/.docky/config.yml
docky.yml file is missing
```

(using docky-3.0.5 installed from github)

**Comment by sebastienbeau** [comment]
I have decided to remove this cmd, I think it simplier to clone the template directory and it more instructive
